# Generated by Django 4.0.2 on 2022-02-26 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avaatar_alter_user_email_alter_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avaatar',
            new_name='avatar',
        ),
    ]
